version: "3"

services:
  python-base: &python
    image: python:latest
    env_file:
      - bazaar.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - rpd-net
  bazaar-prep:
    <<: *python
    command: >
      bash -c "cd /home 
      && [ -d "./BigData" ] 
      || git clone https://github.com/blobbu/BigData.git 
      ; cd BigData 
      && git pull 
      ; cd data_aquisition
      && pip install -r requirements/csv_to_hash.txt 
      && curl https://bazaar.abuse.ch/export/csv/full/ --output full.zip
      && unzip full.zip full.csv
      && python csv_to_hash.py"

  bazaar-download:
    <<: *python
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: >
      bash -c "cd /home 
      && [ -d "./BigData" ] 
      || git clone https://github.com/blobbu/BigData.git 
      ; cd BigData 
      && git pull 
      ; cd data_aquisition
      && pip install -r requirements/hash_to_binary.txt 
      && python hash_to_binary.py"

  bazaar-save:
    <<: *python
    command: >
      bash -c "cd /home 
      && [ -d "./BigData" ] 
      || git clone https://github.com/blobbu/BigData.git 
      ; cd BigData 
      && git pull 
      ; cd data_aquisition
      && pip install -r requirements/binary_to_hdfs.txt 
      && python binary_to_hdfs.py"
  
  
networks:
  rpd-net:
    external: true