version: "3"

x-disabled:
  python-base: &python
    image: python:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - rpd-net
services:
  bazaar-prep:
  <<: *python
  command: >
    bash -c "cd /home 
    && git clone https://github.com/blobbu/BigData.git 
    && cd BigData/data_aquisition
    && pip install requirements/csv_to_hash.txt 
    && python utils/set_env.py
    && python csv_to_hash.py"

  bazaar-download:
  <<: *python
  deploy:
    replicas: 4
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  command: >
    bash -c "cd /home 
    && git clone https://github.com/blobbu/BigData.git 
    && cd BigData/data_aquisition
    && pip install requirements/hash_to_bin.txt 
    && python utils/set_env.py
    && python hash_to_bin.py"

  bazaar-save:
  <<: *python
  command: >
    bash -c "cd /home 
    && git clone https://github.com/blobbu/BigData.git 
    && cd BigData/data_aquisition
    && pip install requirements/bin_to_hdfs.txt 
    && python utils/set_env.py
    && python bin_to_hdfs.py"
  
  
networks:
  rpd-net:
    external: true