version: '3.8'

services:

  core1:
    image: neo4j:3.5-enterprise
    networks:
      - rpd-net    
    ports:     
      - 7474:7474
      - 7687:7687
      - 6687:6687
    env_file:
      - ./neo4j_env.env
    environment:
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_discoveryAdvertisedAddress=core1:5000  
      - NEO4J_causalClustering_transactionAdvertisedAddress=core1:6000  
      - NEO4J_causalClustering_raftAdvertisedAddress=core1:7000  
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_https_advertised__address=:7474
      - NEO4J_dbms_connector_http_advertised__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:6687      
      - NEO4J_causal__clustering_disable__middleware__logging=false
    volumes:
      - /rpd/neo4j/core1/data:/data
      - /rpd/neo4j/core1/logs:/logs
      - /rpd/neo4j/core1/conf:/conf
      - /rpd/neo4j/core1/plugins:/plugins

  core2:
    image: neo4j:3.5-enterprise
    networks:
      - rpd-net
    ports:
      - 7475:7475
      - 7688:7688
      - 6688:6688
    env_file:
      - ./neo4j_env.env
    environment:
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_discoveryAdvertisedAddress=core2:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=core2:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=core2:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_https_advertised__address=:7475
      - NEO4J_dbms_connector_http_advertised__address=:7688
      - NEO4J_dbms_connector_bolt_advertised__address=:6688   
      - NEO4J_causalClustering_refuseToBeLeader=true
    volumes:
      - /rpd/neo4j/core2/data:/data
      - /rpd/neo4j/core2/logs:/logs
      - /rpd/neo4j/core2/conf:/conf
      - /rpd/neo4j/core1/plugins:/plugins

  core3:
    image: neo4j:3.5-enterprise
    networks:
      - rpd-net
    ports:
      - 7476:7476
      - 7689:7689
      - 6689:6689
    env_file:
      - ./neo4j_env.env
    environment:
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_discoveryAdvertisedAddress=core3:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=core3:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=core3:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_https_advertised__address=:7476
      - NEO4J_dbms_connector_http_advertised__address=:7689
      - NEO4J_dbms_connector_bolt_advertised__address=:6689   
      - NEO4J_causalClustering_refuseToBeLeader=true
      - NEO4J_dbms_backup_enabled=true
    volumes:
      - /rpd/neo4j/core3/data:/data
      - /rpd/neo4j/core3/logs:/logs
      - /rpd/neo4j/core3/conf:/conf
      - /rpd/neo4j/core1/plugins:/plugins

  readreplica1:
    image: neo4j:3.5-enterprise
    networks:
      - rpd-net
    ports:
      - 7478:7478
      - 7690:7690
      - 6690:6690
    env_file:
      - ./neo4j_env.env
    environment:
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causalClustering_discoveryAdvertisedAddress=readreplica1:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=readreplica1:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=readreplica1:7000
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_https_advertised__address=:7478
      - NEO4J_dbms_connector_http_advertised__address=:7690
      - NEO4J_dbms_connector_bolt_advertised__address=:6690
    volumes:
      - /rpd/neo4j/replica1/data:/data
      - /rpd/neo4j/replica1/logs:/logs
      - /rpd/neo4j/replica1/conf:/conf
      - /rpd/neo4j/core1/plugins:/plugins      
 
networks:  
  rpd-net: