version: '3'

services:
  neo4j:
    image: neo4j:3.2.3
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"]
    volumes:
      - ./neo4jplugins:/plugins
      - ./neo4jdata:/data
      - ./neo4jimport:/import
      - ./neo4jconf:/conf
      - ./neo4jlogs:/logs
